### ISSUE TITLE
message interceptors

### ISSUE THREAD

**Issue by Ladicek** [smallrye/smallrye-reactive-messaging#1141]
It would be useful to have a notion of "message interceptors" for cases when you want to apply some cross-cuting logic to all messages on a number of channels (one, more than one, all). I hear from @cescoffier that this was discussed in MP Reactive Messaging, but couldn't find an issue in https://github.com/eclipse/microprofile-reactive-messaging/issues We could perhaps discuss the idea here and build a prototype in SmallRye.

Based on this discussion: https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Use.20RequestScoped-bean.20in.20Kafka-Interceptor

**Comment by cescoffier** [comment]
That was related to https://github.com/eclipse/microprofile-reactive-messaging/issues/72.

**Comment by wicksim** [comment]
Is there any progress on this one? We are still looking for a solution for our problem discussed in https://quarkusio.zulipchat.com/#narrow/stream/187030-users/topic/Use.20RequestScoped-bean.20in.20Kafka-Interceptor. A solution with a CDI-Decorator does not seem to work, maybe because of the needed `@Channel`-annotation. Decorator is just not used.

So I'm still searching for a solution to intercept sending/receiving of Kafka-Messages in a way that I can read some values out of a `@RequestScoped` CDI-bean.

**Comment by ozangunalp** [comment]
Initial implementation by #1856, to improve if in need
