### ISSUE TITLE
Add support for NATS

### ISSUE THREAD

**Issue by mpodlodowski** [smallrye/smallrye-reactive-messaging#1158]
Add support for NATS: https://nats.io/

**Comment by cescoffier** [comment]
That sounds promising. 

* Non-Blocking
I'm a bit afraid of the async support that seems to be async but not non-blocking. Basically, it looks like they offload to a thread pool (kind of a bad idea under load). For the `Dispatcher` we may be able to use a Vert.x context.

* Back-pressure 
The consumer side back-pressure mechanism is not great. At least it tells you you got dropped and we could imagine marking the application as unhealthy (hoping to be restarted). I wonder if there is a way to "pause" the reception instead of being kicked. 

On the producer side, it does not seem to be handled either. There is some cache/flush mechanism (https://docs.nats.io/developing-with-nats/sending/caches). As for the consumer side, we can use their ping/pong to detect connection issues or too much load and force a restart. It's not elegant, but it looks unsupported (I may be wrong, I just read the doc very quickly).

We can start with a simple implementation not doing much around back-pressure and see how it goes.

**Comment by MarcAntoine-Beauvais** [comment]
Any update or workaround found to integrate nats?
I'm looking to integrate nats messaging into a quarkus project.

**Comment by cescoffier** [comment]
No news yet; looking for a contributor that knows NATS enough to build a connector. We can help with the integration, but NATS is in uncharted territory for me.

**Comment by DylanSale** [comment]
FYI for backpressure support, I believe the standard approach with NATS is to use JetStream with a pull based consumer.

The consumer can then request batches of messages when it finishes processing the previous batch, essentially implementing "back pressure", though this doesn't actually slow down the message producers, and just acts as a buffer.

In that way, the consumer client can pull messages at it's leisure. If it's too slow, then the NATS server will deal with the queue overflowing as defined in the [jetstream configuration](https://docs.nats.io/running-a-nats-service/nats_admin/jetstream_admin/streams) and isn't the consumer's concern. Some options are to limit the size or number of messages in the stream, with policies to discard the oldest or newest messages when that limit is reached.

If the intent is to implement proper back pressure that slows down the producer, then I believe this needs to be done as a custom application protocol using reply topics. The producer can then listen for acks on the reply topic and continue emitting once the messages have been consumed. This is much more complex to implement correctly however as NATS without Jetstream isn't really a message queue.

**Comment by turing85** [comment]
Andy news? Were you guys able to speak to the nats-team?

**Comment by thomaswiradikusuma** [comment]
There's https://docs.quarkiverse.io/quarkus-reactive-messsaging-nats-jetstream/dev/ (notice the typo)

**Comment by ozangunalp** [comment]
That's true, I've forgotten to close this one. If you are interested, I invite all to contribute to the Quarkiverse extension.
