### ISSUE TITLE
Sending Message in MutiniyEmitter which returns Uni<Void>

### ISSUE THREAD

**Issue by fritzb** [smallrye/smallrye-reactive-messaging#1230]
In `MutiniyEmitter` interface, there exist a method below to send message M, and unfortunately it is subscribed and is not returning Uni<Void>
`<M extends Message<? extends T>> void send(M msg);`

I'm proposing to add a new method below to assist sending message M which returns Uni<Void>.

`<M extends Message<? extends T>>  Uni<Void> send(M msg);`

This is useful for sending Kafka message where the API user wants to attach a Metadata. A concrete example is to send a message into various topics, or have ability to specify message key to manipulate Kafka partition distribution.

**Comment by cescoffier** [comment]
Unfortunately, that new method would conflict with the existing one (Java signature). So, we would need another name. Also, if the passed message is configured with custom ack and nack, implementing such support would erase them, which can be dangerous (that's the reason why this method does not return a Uni).

**Comment by fritzb** [comment]
Sorry, I'm new to the framework. Could you explain how would ack/nack will have to be erased ?
If custom ack/nack can't be supported, how about throwing Illegal Argument exception when configured ?

**Comment by cescoffier** [comment]
ack/nack functions are configured on the Message. They are called when the message is acknowledged positively or negatively. 

When using send(Payload), we create a basic message with the ack and nack configured to report to the produced Uni. For a payload, it's fine because no one except the framework can pass the ack and nack:

```
//pseudo code
return Uni.createFromEmitter(emitter -> {
     emitter.send(Message.of(payload, () -> emitter.complete(), failure -> emitter.fail(failure));
}
```

If a add the method (which would need another name) we can't really do this because the passed Message could have configured the ack and nack. We can't really check if it's set or not when using the method. They are Supplier (and even the default message has its own Supplier). Typically we can't have this:

```java
Message<T> message = Message.of(payload, () -> ack(), failure -> nack(failure));
Uni<Void> uni = emitter.send(message);
```

Indeed, the `send` method needs to be notified when the message is acked/nacked and for this, it would need to configure the ack and nack method. If we use `message.withAck(...).withNack(...)`, we would erase the configured value from above.

Also, if you pass a custom message implementation, we would not be able to configure the ack and nack methods (event if not set) without changing the message type.

**Comment by fritzb** [comment]
Thanks for the explanation. I'm closing this issue.
