### ISSUE TITLE
[Question] What does OnOveflow.Strategy.NONE actually do ? 

### ISSUE THREAD

**Issue by GauthierHacout** [smallrye/smallrye-reactive-messaging#1337]
Hello, 

Firstly if this is not a place to ask questions, don't hesitate to tell me. I couldn't find the answer I'm seeking in the documentation: https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/2/emitter/emitter.html#emitter-overflow

And I wasn't 100% sure of what I was reading in the code:
```
static final class IgnoreBackPressureMultiEmitter<T> extends BaseMultiEmitter<T> {
        IgnoreBackPressureMultiEmitter(MultiSubscriber<? super T> downstream) {
            super(downstream);
        }

        public MultiEmitter<T> emit(T item) {
            this.downstream.onItem(item);

            long r;
            do {
                r = this.requested.get();
            } while(r != 0L && !this.requested.compareAndSet(r, r - 1L));

            return this;
        }
    }
```

So I figured it was best to ask the people who are the most knowledgeable on the subject ! The ones who developed it !

I understand that the NONE Onverflow Strategy is supposed to `ignore the back-pressure signals letting the downstream consumer to implement a strategy.`. But it's a bit vague to me (maybe because I'm not a native english speaker) does it actually mean that there's no buffer & messages are sent one by one after they were acknowledged ? 

What happens if I try to send 1000 message/s & the downstream can only handle 100 message/s for example ?

I'm a new user of Quarkus & trying to persist a CSV file into Kafka led me to the Emitter & the Overflow strategy ! Everything is working fine but I feel like I didn't quite understand this particular thing ! 

Thank you in advance for helping !

**Comment by cescoffier** [comment]
Reactive Messaging handles reactive streams (https://www.reactive-streams.org/) and enforces the reactive streams protocol especially back-pressure. When using an emitter, you can't "control" the pace, so we need to apply an overflow strategy that defines what happens if the emitter tries to send more than what the application can handle. 

The `none` strategy sends the items as they come without any flow control (`this.downstream.onItem(item);`), which means that the downstream consumer may receive more items than its capacity. Depending on the application, it's not a problem, especially if the downstream consumer can handle the load. If the consumer has a strict capacity limit, I would not recommend this strategy.
