### ISSUE TITLE
What is the difference between Strategy.NONE and Strategy.MANUAL for Kafka connector?

### ISSUE THREAD

**Issue by PyAntony** [smallrye/smallrye-reactive-messaging#1624]
Hi,

I can't find any difference when using any of these 2 acknowledgment strategies. Specifically, for these 2 commit strategies: throttled and latest, what changes when using NONE or MANUAL? both seem to be doing exactly the same thing.

**Comment by ozangunalp** [comment]
Acknowledgement strategies are applicable depending on the signature of your channel. 
For example, when your signature accepts a `Message` Manual acknowledgement is the default strategy, and if it accepts payloads, Manual strategy is not applicable.

You can find an exhaustive list of how that applies in the [Reactive Messaging specification](https://download.eclipse.org/microprofile/microprofile-reactive-messaging-2.0/microprofile-reactive-messaging-spec-2.0.html#_positive_acknowledgement).

With the NONE strategy, you can explicitly choose not to apply default pre/post-processing acknowledgement.

As for commit strategies, whether you choose manual or none, if you handle ack's manually through `Message` API commit strategy will be called.

**Comment by PyAntony** [comment]
Thank you for replying. I have a few questions:

1) The web site (https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.9/index.html) does not contain all the information in the link you posted above. Is the link you posted more "up to date"?

2) Documentation indicate that the following function is incorrect (I understand the reason):
```java
@Incoming("in")
@Acknowledgment(Acknowledgment.Strategy.MANUAL)
public void process(Message<I> msg) {
  System.out.println("Got message " + msg.getPayload());
}
```
Will the system print any WARN or ERROR message indicating the error? I mean right when the function is called, not the health verification enforced by "throttled.unprocessed-record-max-age.ms".

3) I understand that there is a health verification (kafka connector) when using the "throttled" commit strategy. So with this strategy I am required to ack() all messages (the system informs me that some messages are missing ack() after some time). If I change to "latest" or "ignore strategy", am I still required to ack() ALL messages? What will happen if I don't?

Just to clarify question 3, from the website (https://smallrye.io/smallrye-reactive-messaging/smallrye-reactive-messaging/3.9/kafka/kafka.html) I can infer that if I switch to "latest" or "ignore strategy" I am no longer required to ack() all messages, specially from this part: "If high-throughout is important for you... set enable.auto.commit to true and annotate the consuming method with @Acknowledgment(Acknowledgment.Strategy.NONE)". It does not tell me that I need to keep acknowledging ALL messages.

(I am asking all this cause' I have developed something with this framework and I worry about having OutOfMemory errors when in production).

**Comment by cescoffier** [comment]
About 1., the content is also available on https://smallrye.io/smallrye-reactive-messaging/3.14.1/concepts/signatures/. It is the most up-to-date version because while we implement the specification, we also offer more features. 

About 2. The reason is that it's dangerous. Indeed, you cannot acknowledge the message, as acknowledgment is async, but you implemented a synchronous method. We want to prevent users from doing `msg.ack().toCompletableFuture().join`, as the whole system would collapse if you do so. 
This method signature is rejected when your application starts. 

About 3. In general, always ack your message. It's better to ack the message and uses the `ignore` strategy than not acknowledging messages. In the case of `latest,` if you do no ack, every time your application or one of its replicas restart, it will reprocess all the messages stored in the topic (that's not all the messages, because of the retention strategy). If you use `ignore,` it will also do that, but even if you ack, nothing will happen. It never commits the offset. In ((% of the case, that's NOT what you want. There are use cases, but they are very narrow. 

BTW, I need to update the website about high-throughout. While it was the case before, this should not be recommended anymore. In addition, you may lose messages (because of the auto-commit), so probably not what you want. As I said, I would recommend always acknowledging messages and using the appropriate commit strategy. 

The throttle strategy will not do an OOM; it will inform you before missing acknowledgments.

Also, most of the time, acknowledging happens automatically; only customize it when the default is not enough for your use case. I have seen use cases where we need to do that. However, it's a tiny minority.

**Comment by PyAntony** [comment]
so, for your answer in number 3, assuming this is exactly what I want ("every time your application or one of its replicas restart, it will reprocess all the messages stored in the topic"), if I use `latest` or `ignore` and I never commit, I will NOT get an OOM correct?

**Comment by PyAntony** [comment]
thank you!
