### ISSUE TITLE
MQTT get value of Wildcard topic

### ISSUE THREAD

**Issue by indiealexh** [smallrye/smallrye-reactive-messaging#1857]
Is there a way to get the topic a message is received from when subscribing to a wildcard topic?

e.g. When subscribed to `devices/#` on the incoming can I get the full topic string `devices/00:00:00:00:00:00`

**Comment by cescoffier** [comment]
not very elegant (MQTT does not have metadata support yet), but you need to receive a `ReceivingMqttMessage`. Be aware it's a `Message` and not a payload anymore.

**Comment by indiealexh** [comment]
> ReceivingMqttMessage

Thank you for the quick response!

**Comment by fkellner** [comment]
Is there any way to mock which MQTT topic a message is sent from via the in-memory-connector?

Since I cannot construct a ReceivingMqttMessage, I tried mocking it with Mockito, but I do not quite understand the finer details of the getMetadata (and other Interface methods), and without mocking these it does not work.

**Comment by fkellner** [comment]
Nvm, found a way: When I consume an `MqttMessage` instead of a `ReceivingMqttMessage`, I can construct an `MqttMessage.of(topic, payload)` and send it via the inMemoryConnector (will then be a `SendingMqttMessage` at Runtime).
