### ISSUE TITLE
RabbitMQ  - Add arguments to exchange

### ISSUE THREAD

**Issue by MaysonD** [smallrye/smallrye-reactive-messaging#2038]
Would be nice to have possibility to set arguments  for exchange. 
<img width="1641" alt="image" src="https://user-images.githubusercontent.com/22799702/211154001-4f18de40-4998-4060-82e3-4ee088635ae6.png">
Arguments can be different screenshot just for example

For now it is not possible to configure plugin like this https://blog.rabbitmq.com/posts/2015/04/scheduling-messages-with-rabbitmq. 
In code used only simple declareExchange without arguments with possible configurations

**Comment by umarhussain15** [comment]
Hi, is there any update on when this feature will be added to the library. 
We want to bind to header exchange from quarkus but there is no option to add arguments for the incoming queue

**Comment by mprunier** [comment]
Hi,
I haven't opened a new ticket because the title is exactly what I would have used.
We are using exchange headers with the key/value pair "x-match"=all, along with some other values to bind our queue and exchange.
This particular use case is not supported in the library (refer to the [documentation](https://www.rabbitmq.com/tutorials/amqp-concepts.html) on Headers Exchange).
Additionally, the default routing key is "#" and it doesn't seem possible to disable it. However, we don't use it.
![image](https://user-images.githubusercontent.com/124352239/232063084-b0bea3aa-6e91-4705-9855-4f528fa3bb02.png)
Do you know if an implementation of this is planned ?
