### ISSUE TITLE
Option health-topic-verification-enabled is confusing and alternative implementation proposal 

### ISSUE THREAD

**Issue by vietk** [smallrye/smallrye-reactive-messaging#2048]
Hello, I would need some advices regarding the health checks and more precisely the startup probe.

From the documentation we can enforce topic verification using the configuration `health-topic-verification-enabled` on both consumer and producer side.
This option force different behaviours on producer/consumer side and startup/readiness probes.
Looking at the documentation of the option, I was thinking that the startup probes actually check that topics are well created on the broker. 

> **health-topic-verification-enabled:**
>> Whether the startup and readiness check should verify that topics exist on the broker. Default to false. Enabling it requires an admin client connection.

Instead, by looking at the code we can see that the startup probe [is just listing the topics, without doing anything else](https://github.com/smallrye/smallrye-reactive-messaging/blob/main/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/health/KafkaSinkHealth.java#L72) and this for each channel

I am not very interested about startup probes on consumer side, I think the readiness probes is already performing a good job checking the assignment of partitions, it's quite fast if the client has been connected and have assigned partitions.

On producer side, instead of having the startup probes checking for topics, it's actually the readiness probes that check for topics existence (using an admin client connection), but this has drawbacks : this can lead the application to miss readiness probes because listing topics is a time consuming operation. That time probably depends of the number topic present in the cluster. So it can happen that we have to increase readiness probes timeout for some of our reactive messaging based applications.

So my question is, what is the aim of just listing the topics on the producer startup probe and does the documentation of the option is really accurate with the current behaviour?

Also I would challenge the actual behaviour with the following : 
- Startup probe check that topics actually exists on the broker, long operation but acceptable at startup
- Readiness probe check that the connection with the broker is still established and no error occurred so far. 

Thanks for your time.
Regards

**Comment by ozangunalp** [comment]
Hi @vietk,

Thank you for the detailed description. 

> On producer side, instead of having the startup probes checking for topics, it's actually the readiness probes that check for topics existence (using an admin client connection), but this has drawbacks : this can lead the application to miss readiness probes because listing topics is a time consuming operation. That time probably depends of the number topic present in the cluster. So it can happen that we have to increase readiness probes timeout for some of our reactive messaging based applications.

I can understand the issue, listing all topics can be long, that's why there is a timeout config. 

The idea for the startup probe using the admin client was to check that the broker is accessible. The implementation is the same for consumer and producer channels and does a list topic names on the broker, without verifying the existence of particular topics. 

I think overall your suggestion makes sense for the producer channels. It'll be a breaking change. 
Alternatively for your issue, we can use another Admin client API that is less dependent on the number of topics. 
I can think of describe cluster for checking connection and describe topic to check existence of a particular topic. 

WDYT? 

BTW processing errors are checked by the liveness probe.

**Comment by vietk** [comment]
Hello 

Thanks for your response.

> I can understand the issue, listing all topics can be long, that's why there is a timeout config.
Having reached a timeout would have been exactly the same has receiving the list of topics after the timeout of the readiness probe => microservice will not be ready. It's not very handy ... 

> I think overall your suggestion makes sense for the producer channels. 
It could be useful to have it for both incoming and outgoing channels. Having different probes implementation can be miss leading: you have to reason about incoming/outgoing and act differently when you are a operating the application
If probes are implemented the same way it's less complicated 

> Alternatively for your issue, we can use another Admin client API that is less dependent on the number of topics.
I can think of describe cluster for checking connection and describe topic to check existence of a particular topic.
> WDYT?

Yeah that would be helpful, someone already had an issue with [admin client too long to respond](https://github.com/quarkusio/quarkus/issues/23948) on the KafkaStreams extension when there's a lot of topic in the cluster.

But I came to another conclusion by looking at the code of Health feature: One external call to admin client is done for each channel, might not be harmful for streaming applications (it's only 2 channels) but for applications with more topics it can be issue. I can open another issue if you something can be done, for example: make only one call and feed the health probes based on the result of that call. This is more or less what is done for KafkaStream extension.

That's a lot of things, but I would be interested by your thoughts on all of this

Regards
Kevin

**Comment by ozangunalp** [comment]
Hi @vietk,

I've started a rework of kafka health checks following our discussion. But I was sidetracked by the latest release. 

> It could be useful to have it for both incoming and outgoing channels. Having different probes implementation can be miss leading: you have to reason about incoming/outgoing and act differently when you are a operating the application
> If probes are implemented the same way it's less complicated

I agree, that's why the startup check on both consumer and producer did a `listTopics`. 
But for the readiness check, I think what we have on the consumer side for checking the partition assignments is satisfactory: If the client is not assigned any partitions it'll be KO.

> Yeah that would be helpful, someone already had an issue with https://github.com/quarkusio/quarkus/issues/23948 on the KafkaStreams extension when there's a lot of topic in the cluster.

I was unable to reproduce this locally, which is not surprising. But it does look like common sense. We can use describeTopics for both consumer and producer startup checks.

> But I came to another conclusion by looking at the code of Health feature: One external call to admin client is done for each channel, might not be harmful for streaming applications (it's only 2 channels) but for applications with more topics it can be issue. I can open another issue if you something can be done, for example: make only one call and feed the health probes based on the result of that call. This is more or less what is done for KafkaStream extension.

The easy remediation for that is to disable the client-based health check for some channels.

----

So to summarize here are the changes we can bring shortly: 

Incoming (consumer) channel topic-verification health checks:
- Startup: Change `listTopics` to `describeTopics` to check the existence of the topic to subscribe. **Breaking change**
- Readiness: Keep consumer assignment check.
- Liveness: Keep

Outgoing (producer) channel topic-verification health checks:
- Startup: Change `listTopics` to `describeTopics` to check the existence of the topic to publish. **Breaking change**
- Readiness: Change `listTopics` with existence check to `describeCluster` to verify the cluster is still reachable. **Breaking change**
- Liveness: Keep

When topic-verification is not enabled, health checks verify the Kafka client's internal connection count metric.
Currently `health-topic-verification-enabled` flag enables the Kafka client checks on both readiness and startup probes. For ease of use, we can also add another flag to control them separately per channel.
