### ISSUE TITLE
RabbitMQ - Missing 'requeue' strategy on rejection/failure of rabbitmq message consumer

### ISSUE THREAD

**Issue by themanojshukla** [smallrye/smallrye-reactive-messaging#2200]
**Introduction:** 

As per the RabbitMQ specifications (as mentioned on https://www.rabbitmq.com/nack.html),

> The [AMQP 0-9-1 specification](https://www.rabbitmq.com/specification.html) defines the basic.reject method that allows clients to reject individual, delivered messages, instructing the broker to either discard them or **requeue them**.

The example also demonstrates the plain Java way of requeuing the consumed message with negative delivery to the broker.

> GetResponse gr = channel.basicGet("some.queue", false);
channel.basicNack(gr.getEnvelope().getDeliveryTag(), false, true);

**Problem Statement:**

The current implementation of by RabbitMQ broker by this project does not honor the requeue strategy.

The `failure-strategy` supports only 3 modes: (https://quarkus.io/guides/rabbitmq-reference)

> The failure strategy to apply when a RabbitMQ message is nacked. Accepted values are fail, accept, reject (default).

While digging down more into source code, I found:

````  
    /**
     * Rejects the message by nack'ing with requeue=false; this will either discard the message for good or
     * (if a DLQ has been set up) send it to the DLQ.
     *
     * @param reason the cause of the rejection, which must not be null
     */
    public void rejectMessage(Throwable reason) {
        holder.getNack(this.deliveryTag, false).apply(reason);
    }
````

The above implementer only encouraged the Dead Letter Queue routing for redelivery, but that is not the thing that everyone might want.

**Proposals:**

Can we introduce one more failure-strategy > requeue?

That can do almost exact same thing but instead of passing the `requeue=false`, it will send `requeue=true`.

Or please suggest any other approach to overcome this?

**Comment by michaelkoetter** [comment]
`requeue` can lead to a requeue/delivery loop if all consumers reject+requeue a message. 

So typically a consumer will track the number of redeliveries and then a) reject the message for good or b) delay the reject+requeue operation for subsequent redeliveries (or a combination of both), otherwise it might end up very busy and the queue could become totally stuck.

If `IncomingRabbitMQMessage#rejectMessage` simply had an additional `requeue` argument this would then allow us to write a custom strategy, which seems easy enough. Maybe also add a note somewhere that `requeue` might be risky 😄

**Comment by themanojshukla** [comment]
Thanks for comment @michaelkoetter 

> requeue can lead to a requeue/delivery loop if all consumers reject+requeue a message.

I think, this is already a known fact but still there are some work/message that are too critical to "let-go (reject)" or to "handle somewhere else (dead-letter-queue)". And as per requirement, the consumer MUST keep trying until it passes. If one uses requeue, it should be assumed that they know the re-delivery or resource business impact. That's what it is meant for. 100% Agreeing to the note part that `requeue` might be risky.


> If IncomingRabbitMQMessage#rejectMessage simply had an additional requeue argument this would then allow us to write a custom strategy.

That's a nice idea but I still think that introducing the `requeue` as new strategy goes in-parallel to rabbitmq specifications, and those who already know/using `requeue` based architecture in other lang/frameworks (eg. Spring, NodeJS, etc) should not be asked to write custom strategy if switching to quarkus/smallrye . What say?

> So typically a consumer will track the number of redeliveries and then a) reject the message for good or b) delay the reject+requeue operation for subsequent redeliveries (or a combination of both), otherwise it might end up very busy and the queue could become totally stuck.

This one is indeed the custom strategy, since you know the impact of your application requirements you can decide the better flow "a", or "b or "combination of both" or "mabe c". But the standard rabbitMQ `requeue` specification should be like a standard strategy in smallrye too, right?

**Comment by kdubb** [comment]
This might be better added as a special case to the RabbitMQ connector.

I believe all that is needed would be to add a flag to the `IncomingRabbitMQMetadata`. The consumer can set the flag and then `nack` as usual.

Unless all other messaging systems support something equal to "Nack with Requeue" then this wouldn't affect anything other connector.

**Comment by kdubb** [comment]
Just to be clear... I am not a proponent of using `requeue`. As stated by @michaelkoetter this can quickly become a problem that stops all processing. I view this as a developer shortcut (sorry if that sounds harsh) because there are much better ways to achieve this. That being said I am a proponent of allowing use of the full feature set of a server when possible.

We use RMQ quite heavily and in certain instances require complex routing _and_ reliability. To do this we have three queues (`a`, `b`, `c`) with `a` dead-lettering to `b` and `b` dead lettering to `c`. `a` is the target from the exchange `b` is essentially a delay queue, and `c` is an overflow queue. As nodes process messages, `a` messages with non-fatal errors are posted to `b` with an incremented `retry-count`. `b` messages with non-fatal error are posted back to `b` (unless the `retry-limit` for the message is exceeded), and `c` messages are processed by a special node that serializes them "long term" to be reposted after error conditions are fixed.

I'm simplifying things quite a bit but I only explain this to say that... queuing messages with reliability is really complex. If as you said:

> And as per requirement, the consumer MUST keep trying until it passes.

Then `requeue` will absolutely not achieve this goal for any system that needs it.

**Comment by michaelkoetter** [comment]
> I believe all that is needed would be to add a flag to the `IncomingRabbitMQMetadata`. The consumer can set the flag and then `nack` as usual.

That's a good idea, this way the consumer can implement a back-off strategy if desired and decide on a case-by-case basis whether to requeue a message.
`IncomingRabbitMQMessage#rejectMessage` still needs to expose the `requeue` flag I think, so the `reject` failure-strategy can be adjusted to make use of the new metadata. As this is a public method, would it be better to overload it to avoid breaking existing code? As far as I can see it is only used by the failure-strategy, but of course there could now be custom strategies out there that might break if the method signature changes.

**Comment by themanojshukla** [comment]
Thanks @kdubb for the suggestions.

All I was trying to advocate for **_the feature_** (also specification by RabbitMQ) particularly, and not for what's '_the better way to.._' solve a complex domain/application problem. The former one is that `requeue` feature that is missing, and we all agreed on this. The later one sounds like an "opinion" (at least to me) that one should follow to avoid queue busyness/looping issue that comes with `requeue`.

The reasons you guys gave above to avoid using `requeue` without any terminal approach are absolutely valid. But does it originate from this repository as a new concept? - No. It's already a queue feature by ReabbiMQ broker itself. And this repository is a client to the broker. Ideally, clients should/can do improvisation on top the specification but they MUST support the specification features even though it comes with a warning sign, shouldn't they?

The idea for having another flag for `requeue` and consumer-based decision is just great.

**Comment by michaelkoetter** [comment]
Just to be clear, I‘m also looking for a way to use requeue 😄 
My point was basically that exposing it as a strategy without further options (ie. back-off strategy) would probably not be very useful for complex applications.
But the flag and consumer-based decision would work great for us. If no one is working on this yet, I could create a pull request next week (currently on vacation).

**Comment by michaelkoetter** [comment]
On closer examination I saw there's already a `nack(Throwable, Metadata)` method, which is supposed to supply "additional nack metadata". I think this is even better than using `IncomingRabbitMQMetadata` for the requeue flag.

**Comment by cescoffier** [comment]
Hold on on using that method. @ozangunalp mentioned to me some issues with it.
