### ISSUE TITLE
Add per channel `health-enabled` connector attribute to RabbitMQ

### ISSUE THREAD

**Issue by ozangunalp** [smallrye/smallrye-reactive-messaging#2326]
From https://github.com/quarkusio/quarkus/issues/36398

**Comment by derari** [comment]
two questions before I start working on this:

what should the configuration properties for this feature look like? global regexes, pr properties on each channel (and maybe a global default)?

wellness checks are not part of the microprofile health standard. could we still have equivalent getWellness methods in all the respective places, so that a wellness check can be added in the quarkus package?

**Comment by ozangunalp** [comment]
You can check how it is done in Kafka and MQTT connectors, it is basically a per channel attribute which affects how the health probe is returned : 
https://github.com/smallrye/smallrye-reactive-messaging/blob/c42e7ac4966ebd2cd1705d3f7b4793fae496ff2b/smallrye-reactive-messaging-kafka/src/main/java/io/smallrye/reactive/messaging/kafka/KafkaConnector.java#L49

https://github.com/smallrye/smallrye-reactive-messaging/blob/c42e7ac4966ebd2cd1705d3f7b4793fae496ff2b/smallrye-reactive-messaging-mqtt/src/main/java/io/smallrye/reactive/messaging/mqtt/MqttConnector.java#L35

I am not familiar with the wellness check, do you have a link where I could read on it?

**Comment by derari** [comment]
here is a link about "wellness" health: https://smallrye.io/docs/smallrye-health/3.0.1/wellness.html

basically, instead of (or in addition to) `health-enabled: true|false`, I would also like to support something like `health-enabled: wellness, startup`

**Comment by ozangunalp** [comment]
I don't see how wellness applies to reactive messaging channels. 
Readiness, liveness and startup map to kube health checks and are implemented by RM channels.
If there is a custom need the application can implement a wellness check.

**Comment by derari** [comment]
Why wellness can be important for reactive channels:
If, for example, the RabbitMq server is unreachable, this can not be fixed by restarting the application, so I don't want a connection liveness check. If the connection is not required for serving requests (for example, my application only consumes from RabbitMq), then it should not be a readiness check either. I still want my application to communicate it needs help, though, so wellness or group checks are the only option.

Of course, everything can be implemented in the application. The question is, how much do we want to support out of the box?
