### ISSUE TITLE
Utilize Vert.x in core

### ISSUE THREAD

**Issue by kenfinnigan** [smallrye/smallrye-reactive-messaging#423]
It would be beneficial if we switched to using Vert.x inside the core of SmallRye Reactive Messaging for a number of reasons:

- Take advantage of a library that is designed around "reactive" and has been around for years
- Ability to use a slightly higher-level API that abstracts away a lot of things we don't need to be considered with. An example of this is being able to call a Vert.x method to execute code in a blocking fashion for supporting `@Blocking`, as opposed to us coding all that handling into this project.
- Simplify existing code that could take advantage of Vert.x functionality directly instead of replicating it.
- Reduce possible bugs by using a heavily tested library for "reactive"

There are probably other reasons I didn't think of as well.

Would appreciate comments on whether this is good, bad, or indifferent to the community.

**Comment by cescoffier** [comment]
A big +1! IT would drastically simplify the connectors code and also somewhat the implementation.

**Comment by hutchig** [comment]
This was raised hours after (straight after really if you account for timezones) https://github.com/OpenLiberty/open-liberty/issues/10813#issuecomment-586865685 , which suggests a portability SPI for SmallRye, was written. It is a moot
point whether this is a co-incidence but either way - will depe3nding on Vert.x not make SmallRye less consumable by other MicroProfile implementations?

**Comment by kenfinnigan** [comment]
I wasn't aware of the OpenLiberty issue. Does that talk about a compatibility layer for all SmallRye projects, or just this one?

As long as Vert.x, or Netty, is an implementation detail that isn't exposed to developers, in what way would it make SmallRye implementations less consumable? We're not starting servers with Vert.x, but simply using it as a Reactive toolkit to simplify the implementation code.

There are no plans around impedance between SmallRye and OpenLiberty, mostly because the community hasn't been informed of any. If the OpenLiberty team wants to ensure that SmallRye implementations, whichever ones they might be, are consumable by OpenLiberty as things change then it would be appreciated if the team actively engaged with the community to discuss problems and solutions.

I appreciate your reaching out on this thread, but without details of what is needed, and why, it's difficult for the community to decide on an appropriate direction.

**Comment by hutchig** [comment]
Thanks for your quick reply Ken.
That OpenLiberty issue (10813) is only talking about MicroProfile Reactive Messaging Connectors but I can't see it as anything but a 'good thing' to reuse SmallRye components as much as possible - so going forwards I think it makes sense for each component of an MP implementation to ask 'why not' initially rather than 'why' of if. I guess an important point is that we don't want this secondary/tertiarty consumption to be accomodated if it somehow means we get some sort of 'lowest common denominator' of function, a convoluted design or duplicate function in any single stack.

For 'less consumable' I specifically am referring to a reduction of ease that SmallRye components can be consumed in non Redhat implementations, and even more specifically in J*EE based ones like OpenLiberty when compared to not basing on Vert.x as is. 

I know we are not starting servers, but we are getting into proposing using Vert.x to create/control other assets that are more than just internal-data structutes independantly from the host (user facing) platform. 

For example, the concrete case you give above is embedded in the second of your
4 blist points (the other 3 are generally reasonably sounding fillers-not-killers so I don't have
any worries about agreeign with any of them). 

So in using Vert.x to help in the implementation of `@Blocking` my toddler understanding
of Vert.x maps this ultimately to https://vertx.io/docs/kdoc/vertx/io.vertx.reactivex.core/-vertx/execute-blocking.html  "using a thread from the worker pool". 

So the concrete requirement, to consume such a mechanism in a J*EE context, is to be able to fullfill the expected J*EE semantics for a thread from this 'worker pool' such as one might expect with Threads from a J*EE ManagedExecutor or at least have some defined semantic that we can explain to users so that everyone's expectations line up. 

Currently though, Vert.x threads have their own, independant notion of 'context' (evolving for the better in Vert.x 4 but still not really overlapping with J*EE to my knowledge).

So, for example for threads, the ideal requirement (in my own view) is to have Vert.x thread context, MicroProfile context and J*EE context (Principle etc) understood and lined up in a way that we can explain to users and which preserves users 'common sense' expectations (when they don't read our explainations) of what they can expect to be present, and not present,  as 'context' on a thread their application Java is running on.

So I am aware that Vert.x concretely subclasses Netty's FastThreadLocalThread
https://github.com/eclipse-vertx/vert.x/blob/4037b11287aa7c5c9cd9ce37321f12da42f3246a/src/main/java/io/vertx/core/impl/VertxThread.java#L21 
and any SmallRye implementation of @Blocking (which I don't think is in any common
spec currently) that uses Vert.x for the impl is likely to run on one of those. 

So a concrete requirement might be that if we were ever to push @Blocking into the spec 
I would hope to have sufficient hooks/callbacks into the Vert.x worker pool thread
lifecycle to enable things to 'fit' from a J*EE point of view.

I admit that I have not investigated enough how Quarkus solves this for MP Context
to know what Ken has in mind above to handle that for Vert.x worker pool threads.

**Comment by kenfinnigan** [comment]
I don't know if the current code does this, but I would suspect the easiest solution is for a runtime to register a means by which threads are created/used by SRye RM.

So when implementing `@Blocking`, Quarkus would use a Vert.x Worker pool thread (not necessarily creating one), but OpenLiberty, or anything else, could define the Executor thread pool to have one created, or whatever means they wanted for threads to be created/used.

I'm being a bit handy-wavy with this, but I think the theory holds.

**Comment by hutchig** [comment]
Thanks Ken I will have a look at how/if/how-could Vert.x Worker pool threads might nicely with Liberty ManagedExcecutor threads. (Probably on Tuesday when I am back in the office). 

Is the design for how JBoss EAP J*EE Contexts are going to be honoured for Vert.x Worker pool threads already sorted?

**Comment by kenfinnigan** [comment]
There currently isn't a specific design for WildFly/EAP. @kabir has been doing some investigations around adding reactive bits to WildFly, but not sure if there's a defined plan as to when that might happen

**Comment by kabir** [comment]
My WIP lives here: https://github.com/kabir/wildfly-mp-reactive-galleon-pack

I've not really done any investigation into pools etc. Also context-propagation passes the TCK we are missing a bunch of stuff in WildFly to bring it to feature parity with Quarkus. Also, I need some better tests/examples integrating the three specs

**Comment by hutchig** [comment]
Thank you very much @kabir, I am back at work today and will have a good look at the galleon pack and ponder how a Netty:Vert.x:SmallRye stack might fit with (our) J*EE. I might start with how Vert.x contexts are changing for v4.

**Comment by Emily-Jiang** [comment]
Thank you @hutchig for bringing me to this discussion! Sorry for joining in late due to travelling last week and a lot of catching ups! 

As you may know @kenfinnigan @cescoffier, Open Liberty would like to collaborate MicroProfile implementations via SmallRye, such as SmallRye Reactive Messaging. We also have plans to consume most of SmallRye connectors in Open Liberty via [this](https://github.com/OpenLiberty/open-liberty/issues/10813) issue. 

At the moment, we have not managed to put Vert.x into Open Liberty as yet because Open Liberty uses Channel Framework instead of Netty, which Vert.x has a  hard dependency on. Open Liberty has also different thread pool approach from Netty. This issue suggest to use Vert.x in the core of SmallRye, which might put Open Liberty into the situation where SmallRye cannot be consumed by Open Liberty any more.

Having said that, based on my conversation with @cescoffier on the usage of Vert.x, Liberty team is prototyping to use Vert.x and Netty as libraries with the hope to get SmallRey Connectors to work on Open Liberty. We have not gone very far as yet.

At this point of time, is it possible to ask you to rethink the use case to see whether it is possible not to use the thread pools (https://github.com/eclipse-vertx/vert.x/blob/4037b11287aa7c5c9cd9ce37321f12da42f3246a/src/main/java/io/vertx/core/impl/VertxThread.java#L21), which effectively forces the consumers to use Vert.x and Netty explicitly? Instead, it might be a good approach to abstract this and allow the consumers to plugin their own thread pool. Thoughts?

**Comment by kenfinnigan** [comment]
The OpenLiberty team is more than welcome to provide a PR to propose what is needed for the use of Vert.x to work in OpenLiberty.

Granted, that won't be possible until the use of Vert.x is actually added to the code.

**Comment by Emily-Jiang** [comment]
Just report back on this. We are investigating to integrate Vert.x to Open Liberty, but from some initial work, it might take some time. Whilst we're investigating whether or not we can consume Vert.x into Open Liberty, could I ask that you hold off doing the integration with Vert.x in the core of SmallRye MP RM and this would prevent us from being able to collaborate on SmallRye?

**Comment by kenfinnigan** [comment]
@Emily-Jiang While it would be great for OpenLiberty to use SmallRye Reactive Messaging all the time, we can't hold back innovation in the implementation.

We're more than happy to create a branch prior to such a PR being merged. OpenLiberty developers can submit PRs to that branch with features added to "master" that is compatible with not incorporating Vert.x until such time as OpenLiberty can utilize Vert.x

**Comment by Emily-Jiang** [comment]
@kenfinnigan thanks for your notes! Staying on an old branch is really no different from not using Smallrye for us. We don’t get benefits on co-development on a shared implementation. Can you please share the code changes so that we can work together with whoever is working on the PR to see how we can make it work for both Quarkus and Open Liberty?

**Comment by kenfinnigan** [comment]
You would get the benefits as you'd be able to submit PRs to the older branch for work done on master when it doesn't rely on Vert.x, or anything else, that OpenLiberty doesn't support. It's not the same as having nothing in common.

When the PR is ready I will link to it here. However, approval and merging of the PR will not be delayed to support changes for OpenLiberty. Any changes that might be required for support in OpenLiberty can be discussed and agreed upon in subsequent PRs.

**Comment by kenfinnigan** [comment]
FYI -> https://github.com/smallrye/smallrye-reactive-messaging/pull/467

**Comment by kenfinnigan** [comment]
Closing as PR is now merged
